// CYItemBase.cpp - í•µì‹¬ ë¡œì§ë§Œ ë‚¨ê¸´ ê¸°ë³¸ ì•„ì´í…œ í´ë˜ìŠ¤ êµ¬í˜„
#include "Items/CYItemBase.h"
#include "Character/CYPlayerCharacter.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SphereComponent.h"
#include "Net/UnrealNetwork.h"
#include "Engine/Engine.h"

ACYItemBase::ACYItemBase()
{
    PrimaryActorTick.bCanEverTick = false;
    bReplicates = true;
    SetReplicateMovement(true);

    // Root Component
    RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));

    // Mesh Component
    ItemMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ItemMesh"));
    ItemMesh->SetupAttachment(RootComponent);
    ItemMesh->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    ItemMesh->SetCollisionResponseToAllChannels(ECR_Block);
    ItemMesh->SetCollisionResponseToChannel(ECC_Pawn, ECR_Ignore);

    // Interaction Sphere
    InteractionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("InteractionSphere"));
    InteractionSphere->SetupAttachment(RootComponent);
    InteractionSphere->SetSphereRadius(150.0f);
    InteractionSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    InteractionSphere->SetCollisionResponseToAllChannels(ECR_Ignore);
    InteractionSphere->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
    InteractionSphere->SetCollisionObjectType(ECC_WorldDynamic);

    // ê¸°ë³¸ê°’ ì„¤ì •
    bIsPickedUp = false;
    ItemCount = 1;
    MaxStackCount = 10;
}

void ACYItemBase::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    
    DOREPLIFETIME(ACYItemBase, bIsPickedUp);
    DOREPLIFETIME(ACYItemBase, ItemCount);
}

void ACYItemBase::BeginPlay()
{
    Super::BeginPlay();

    // ì„œë²„ì—ì„œë§Œ ì¶©ëŒ ì´ë²¤íŠ¸ ë“±ë¡
    if (HasAuthority())
    {
        InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &ACYItemBase::OnSphereOverlap);
        InteractionSphere->OnComponentEndOverlap.AddDynamic(this, &ACYItemBase::OnSphereEndOverlap);
    }
}

void ACYItemBase::OnPickup(ACYPlayerCharacter* Character)
{
    if (!Character || bIsPickedUp || !HasAuthority()) return;

    bIsPickedUp = true;
    
    // ì•„ì´í…œì„ ìˆ¨ê¸°ê³  ì¶©ëŒ ë¹„í™œì„±í™”
    SetActorHiddenInGame(true);
    SetActorEnableCollision(false);
    
    UE_LOG(LogTemp, Warning, TEXT("âœ… Item picked up: %s"), *ItemName.ToString());
}

bool ACYItemBase::UseItem(ACYPlayerCharacter* Character)
{
    if (!Character) return false;
    
    // ê¸°ë³¸ êµ¬í˜„: ì†Œëª¨í’ˆ ì²˜ë¦¬
    if (ItemType == EItemType::Consumable && ItemCount > 0)
    {
        ItemCount--;
        UE_LOG(LogTemp, Warning, TEXT("ğŸ”§ Used item: %s (Remaining: %d)"), 
               *ItemName.ToString(), ItemCount);
        return true;
    }
    
    return false;
}

bool ACYItemBase::CanStackWith(ACYItemBase* OtherItem) const
{
    if (!OtherItem) return false;
    
    // ê°™ì€ í´ë˜ìŠ¤ì´ê³ , ìŠ¤íƒ ê°€ëŠ¥í•˜ê³ , ê³µê°„ì´ ìˆì–´ì•¼ í•¨
    return (GetClass() == OtherItem->GetClass()) && 
           (MaxStackCount > 1) && 
           (OtherItem->ItemCount < OtherItem->MaxStackCount);
}

void ACYItemBase::OnRep_ItemCount()
{
    // ì•„ì´í…œ ìˆ˜ëŸ‰ ë³€ê²½ ì‹œ UI ì—…ë°ì´íŠ¸ ë“±
    UE_LOG(LogTemp, Log, TEXT("Item count updated: %s x%d"), *ItemName.ToString(), ItemCount);
}

void ACYItemBase::OnRep_IsPickedUp()
{
	if (bIsPickedUp)
	{
		SetActorHiddenInGame(true);
		SetActorEnableCollision(false);
	}
	else
	{
		SetActorHiddenInGame(false);
		SetActorEnableCollision(true);
	}
}

void ACYItemBase::OnSphereOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
                                  UPrimitiveComponent* OtherComp, int32 OtherBodyIndex,
                                  bool bFromSweep, const FHitResult& SweepResult)
{
    if (bIsPickedUp) return;

    if (ACYPlayerCharacter* Character = Cast<ACYPlayerCharacter>(OtherActor))
    {
        // UI íŒíŠ¸ í‘œì‹œ
        UE_LOG(LogTemp, Log, TEXT("Player near item: %s"), *ItemName.ToString());
    }
}

void ACYItemBase::OnSphereEndOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
    if (ACYPlayerCharacter* Character = Cast<ACYPlayerCharacter>(OtherActor))
    {
        // UI íŒíŠ¸ ìˆ¨ê¸°ê¸°
        UE_LOG(LogTemp, Log, TEXT("Player left item area: %s"), *ItemName.ToString());
    }
}