// CYTrapBase.cpp - í•µì‹¬ ë¡œì§ë§Œ ë‚¨ê¸´ íŠ¸ë© ê¸°ë³¸ í´ë˜ìŠ¤ êµ¬í˜„
#include "Items/Traps/CYTrapBase.h"
#include "Character/CYPlayerCharacter.h"
#include "Components/SphereComponent.h"
#include "AbilitySystemComponent.h"
#include "AbilitySystem/CYAbilitySystemComponent.h"
#include "AbilitySystem/CYCombatGameplayTags.h"
#include "TimerManager.h"
#include "Net/UnrealNetwork.h"
#include "Engine/Engine.h"

ACYTrapBase::ACYTrapBase()
{
    ItemName = FText::FromString("Base Trap");
    ItemType = EItemType::Trap;
    MaxStackCount = 5; // íŠ¸ë©ì€ ìŠ¤íƒ ê°€ëŠ¥
    
    TrapState = ETrapState::MapPlaced;
    bIsArmed = false;
    
    // ê¸°ë³¸ ì„¤ì •
    TriggerRadius = 100.0f;
    ArmingDelay = 2.0f;
    TrapLifetime = 60.0f;
}

void ACYTrapBase::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
    Super::GetLifetimeReplicatedProps(OutLifetimeProps);
    
    DOREPLIFETIME(ACYTrapBase, TrapState);
    DOREPLIFETIME(ACYTrapBase, bIsArmed);
}

void ACYTrapBase::BeginPlay()
{
    Super::BeginPlay();
    
    // ê¸°ë³¸ ë©”ì‹œ ì„¤ì • (ì‹¤ë¦°ë” ëª¨ì–‘)
    if (ItemMesh && !ItemMesh->GetStaticMesh())
    {
        UStaticMesh* CylinderMesh = LoadObject<UStaticMesh>(nullptr, TEXT("/Engine/BasicShapes/Cylinder"));
        if (CylinderMesh)
        {
            ItemMesh->SetStaticMesh(CylinderMesh);
            ItemMesh->SetWorldScale3D(FVector(0.5f, 0.5f, 0.1f));
        }
    }
}

bool ACYTrapBase::UseItem(ACYPlayerCharacter* Character)
{
    if (!Character || !HasAuthority()) return false;
    
    // ğŸ”¥ ì‹¤ì œ GA_PlaceTrap ì–´ë¹Œë¦¬í‹° ì‹¤í–‰
    UCYAbilitySystemComponent* ASC = Cast<UCYAbilitySystemComponent>(Character->GetAbilitySystemComponent());
    if (!ASC)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ Character has no AbilitySystemComponent"));
        return false;
    }
    
    // íŠ¸ë© ì„¤ì¹˜ ì–´ë¹Œë¦¬í‹°ë¥¼ ì´ íŠ¸ë© ì•„ì´í…œì„ ì†ŒìŠ¤ë¡œ ì‹¤í–‰
    bool bActivated = ASC->TryActivateAbilityByTagWithSource(
        CYGameplayTags::Ability_Combat_PlaceTrap, 
        this  // ì´ íŠ¸ë© ì•„ì´í…œì„ ì†ŒìŠ¤ë¡œ ì „ë‹¬
    );
    
    if (bActivated)
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap placement ability activated: %s"), *ItemName.ToString());
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("âŒ Failed to activate trap placement ability"));
    }
    
    return bActivated;
}

void ACYTrapBase::PlaceTrap(const FVector& Location, ACYPlayerCharacter* Placer)
{
    if (!HasAuthority()) return;
    
    TrapState = ETrapState::PlayerPlaced;
    SetOwner(Placer);
    SetActorLocation(Location);
    
    // í”½ì—… ìƒíƒœë¡œ ë³€ê²½
    bIsPickedUp = true;
    SetActorHiddenInGame(false);
    SetActorEnableCollision(true);
    
    // ì¶©ëŒ ì´ë²¤íŠ¸ ì¬ì„¤ì •
    if (InteractionSphere)
    {
        InteractionSphere->OnComponentBeginOverlap.Clear();
        InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &ACYTrapBase::OnTrapSphereOverlap);
    }
    
    // íƒ€ì´ë¨¸ ì„¤ì •
    GetWorld()->GetTimerManager().SetTimer(ArmingTimer, this, &ACYTrapBase::ArmTrap, ArmingDelay, false);
    GetWorld()->GetTimerManager().SetTimer(LifetimeTimer, [this](){ Destroy(); }, TrapLifetime, false);
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap placed: %s at %s"), 
           *ItemName.ToString(), *Location.ToString());
}

void ACYTrapBase::ArmTrap()
{
    if (!HasAuthority() || TrapState != ETrapState::PlayerPlaced) return;
    
    bIsArmed = true;
    
    // íŠ¸ë¦¬ê±° ë°˜ê²½ìœ¼ë¡œ ë³€ê²½
    if (InteractionSphere)
    {
        InteractionSphere->SetSphereRadius(TriggerRadius);
    }
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Trap armed: %s"), *ItemName.ToString());
    
    // ì‹œê°ì  íš¨ê³¼
    if (GEngine)
    {
        GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Green, 
            FString::Printf(TEXT("%s ARMED!"), *ItemName.ToString()));
    }
}

void ACYTrapBase::OnTrapSphereOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex,
    bool bFromSweep, const FHitResult& SweepResult)
{
    // íŠ¸ë©ì´ í™œì„±í™” ìƒíƒœê°€ ì•„ë‹ˆë©´ ë¬´ì‹œ
    if (TrapState != ETrapState::PlayerPlaced || !bIsArmed || !HasAuthority()) return;
    
    // ì„¤ì¹˜í•œ í”Œë ˆì´ì–´ëŠ” ë¬´ì‹œ
    if (OtherActor == GetOwner()) return;
    
    ACYPlayerCharacter* Target = Cast<ACYPlayerCharacter>(OtherActor);
    if (!Target) return;
    
    OnTrapTriggered(Target);
}

void ACYTrapBase::OnTrapTriggered(ACYPlayerCharacter* Target)
{
    if (!Target || !HasAuthority()) return;
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ TRAP TRIGGERED! %s stepped on %s's trap"), 
           *Target->GetName(), 
           GetOwner() ? *GetOwner()->GetName() : TEXT("Unknown"));
    
    // GAS íš¨ê³¼ ì ìš©
    UAbilitySystemComponent* TargetASC = Target->GetAbilitySystemComponent();
    if (TargetASC)
    {
        for (TSubclassOf<UGameplayEffect> EffectClass : TrapEffects)
        {
            if (EffectClass)
            {
                FGameplayEffectContextHandle EffectContext = TargetASC->MakeEffectContext();
                EffectContext.AddSourceObject(this);
                
                FGameplayEffectSpecHandle EffectSpec = TargetASC->MakeOutgoingSpec(EffectClass, 1, EffectContext);
                if (EffectSpec.IsValid())
                {
                    TargetASC->ApplyGameplayEffectSpecToSelf(*EffectSpec.Data.Get());
                    UE_LOG(LogTemp, Warning, TEXT("âœ… Applied trap effect: %s"), *EffectClass->GetName());
                }
            }
        }
    }
    
    // ë¸”ë£¨í”„ë¦°íŠ¸ ì»¤ìŠ¤í…€ íš¨ê³¼
    ApplyTrapEffect(Target);
    
    // í™”ë©´ ë©”ì‹œì§€
    if (GEngine)
    {
        FString TrapTypeName;
        switch (TrapType)
        {
            case ETrapType::Slow: TrapTypeName = TEXT("SLOWED"); break;
            case ETrapType::Freeze: TrapTypeName = TEXT("FROZEN"); break;
            case ETrapType::Damage: TrapTypeName = TEXT("DAMAGED"); break;
        }
        
        GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Red, 
            FString::Printf(TEXT("%s %s!"), *Target->GetName(), *TrapTypeName));
    }
    
    // íŠ¸ë© ì œê±°
    Destroy();
}

void ACYTrapBase::OnRep_TrapState()
{
    // ìƒíƒœ ë³€ê²½ ì‹œ ì‹œê°ì  ì—…ë°ì´íŠ¸
    if (TrapState == ETrapState::PlayerPlaced)
    {
        SetActorHiddenInGame(false);
        SetActorEnableCollision(true);
    }
}

void ACYTrapBase::OnRep_IsArmed()
{
    // í™œì„±í™” ì‹œ ì‹œê°ì  íš¨ê³¼
    if (bIsArmed && GEngine)
    {
        GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Yellow, 
            FString::Printf(TEXT("%s ARMED!"), *ItemName.ToString()));
    }
}