#include "CYCharacterBase.h"
#include "CYLogChannels.h"
#include "AbilitySystem/CYAbilitySystemComponent.h"
#include "AbilitySystem/CYCombatGameplayTags.h"
#include "AbilitySystem/Attributes/CYCombatAttributeSet.h"
#include "Components/Items/CYInventoryComponent.h"
#include "Components/Items/CYItemInteractionComponent.h"
#include "Components/Items/CYWeaponComponent.h"
#include "GameFramework/CharacterMovementComponent.h"

ACYCharacterBase::ACYCharacterBase(const FObjectInitializer& ObjectInitializer)
{
	PrimaryActorTick.bCanEverTick = false;

	// Item Ïª¥Ìè¨ÎÑåÌä∏Îì§ ÏÉùÏÑ±
	InventoryComponent = CreateDefaultSubobject<UCYInventoryComponent>(TEXT("InventoryComponent"));
	ItemInteractionComponent = CreateDefaultSubobject<UCYItemInteractionComponent>(TEXT("ItemInteractionComponent"));
	WeaponComponent = CreateDefaultSubobject<UCYWeaponComponent>(TEXT("WeaponComponent"));

}

UAbilitySystemComponent* ACYCharacterBase::GetAbilitySystemComponent() const
{
	return CYAbilitySystemComponent.Get();
}

void ACYCharacterBase::BeginPlay()
{
	Super::BeginPlay();
}

void ACYCharacterBase::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	RemoveAbilitySets();
	Super::EndPlay(EndPlayReason);
}

void ACYCharacterBase::InitializeAbilitySets()
{
	if (!HasAuthority())
	{
		return;
	}
	
	if (!CYAbilitySystemComponent.IsValid())
	{
		UE_LOG(LogCY, Warning, TEXT("%s Side: InitializeAbilitySets: AbilitySystemComponent is invalid on %s"), *GetClientServerContextString(this), *GetNameSafe(this));
		return;
	}

	// Í∏∞Ï°¥ Ability Ï†úÍ±∞
	RemoveAbilitySets();

	UCYAbilitySystemComponent* CYASC = CYAbilitySystemComponent.Get();
	
	// Í∏∞Î≥∏ AbilitySet Î∂ÄÏó¨
	for (UCYAbilitySet* AbilitySet : DefaultAbilitySets)
	{
		if (IsValid(AbilitySet))
		{
			FCYAbilitySet_GrantedHandles& GrantedHandles = GrantedAbilitySetHandles.AddDefaulted_GetRef();
			AbilitySet->GiveToAbilitySystem(CYASC, &GrantedHandles);
		}
	}
	
	// Í≤ÄÏ¶ù
	const UCYCombatAttributeSet* FinalCheck = CYASC->GetSet<UCYCombatAttributeSet>();
	if (FinalCheck)
	{
		UE_LOG(LogCY, Warning, TEXT("‚úÖ %s has UCYCombatAttributeSet (MoveSpeed: %f)"), 
			   *GetName(), FinalCheck->GetMoveSpeed());
	}
	else
	{
		UE_LOG(LogCY, Error, TEXT("‚ùå %s still missing UCYCombatAttributeSet!"), *GetName());
	}
}

void ACYCharacterBase::RemoveAbilitySets()
{
	// ÏÑúÎ≤ÑÏóêÏÑúÎßå Ï†úÍ±∞
	if (!HasAuthority())
	{
		return;
	}
	
	if (!CYAbilitySystemComponent.IsValid())
	{
		return;
	}

	UCYAbilitySystemComponent* CYASC = CYAbilitySystemComponent.Get();

	// Î™®Îì† Î∂ÄÏó¨Îêú Îä•Î†• Ï†úÍ±∞
	for (FCYAbilitySet_GrantedHandles& GrantedHandles : GrantedAbilitySetHandles)
	{
		GrantedHandles.TakeFromAbilitySystem(CYASC);
	}
	GrantedAbilitySetHandles.Empty();
}

void ACYCharacterBase::InteractPressed()
{
	if (ItemInteractionComponent)
	{
		ItemInteractionComponent->InteractWithNearbyItem();
	}
}

void ACYCharacterBase::AttackPressed()
{
	// üî• CatchMe Î∞©Ïãù: WeaponComponentÏóêÏÑú Î™®Îì† Í≥µÍ≤© Î°úÏßÅ Ï≤òÎ¶¨
	if (WeaponComponent)
	{
		WeaponComponent->PerformAttack();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("No WeaponComponent found"));
	}
}

void ACYCharacterBase::UseInventorySlot(int32 SlotIndex)
{
	if (InventoryComponent)
	{
		InventoryComponent->UseItem(SlotIndex);
	}
}