#include "CYPlayerCharacter.h"

#include "EnhancedInputSubsystems.h"
#include "Camera/CameraComponent.h"
#include "AbilitySystem/CYAbilitySystemComponent.h"
#include "AbilitySystem/CYCombatGameplayTags.h"
#include "Components/Items/CYInventoryComponent.h"
#include "Components/Items/CYItemInteractionComponent.h"
#include "Components/Items/CYWeaponComponent.h"
#include "Input/CYInputComponent.h"
#include "Input/CYInputGameplayTags.h"
#include "Player/CYPlayerState.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Items/CYItemBase.h"
#include "Items/CYWeaponBase.h"

ACYPlayerCharacter::ACYPlayerCharacter(const FObjectInitializer& ObjectInitializer) 
	:	Super(ObjectInitializer)
{
	CameraBoom = CreateDefaultSubobject<USpringArmComponent>(FName("CameraBoom"));
	CameraBoom->SetupAttachment(GetRootComponent());
	CameraBoom->bUsePawnControlRotation = true;

	FollowCamera = CreateDefaultSubobject<UCameraComponent>(FName("FollowCamera"));
	FollowCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);

	bUseControllerRotationPitch = false;
	bUseControllerRotationYaw = false;
	bUseControllerRotationRoll = false;

	GetCharacterMovement()->bOrientRotationToMovement = true;
	GetCharacterMovement()->RotationRate = FRotator(0.f, 500.f, 0.f);
	GetCharacterMovement()->MaxWalkSpeed = 400.f;
}

void ACYPlayerCharacter::PawnClientRestart()
{
	Super::PawnClientRestart();
	APlayerController* OwningPlayerController = GetController<APlayerController>();
	if (OwningPlayerController && OwningPlayerController->GetLocalPlayer())
	{
		UEnhancedInputLocalPlayerSubsystem* InputSubsystem = OwningPlayerController->GetLocalPlayer()->GetSubsystem<UEnhancedInputLocalPlayerSubsystem>();
		if (InputSubsystem)
		{
			InputSubsystem->RemoveMappingContext(DefaultMappingContext);
			InputSubsystem->AddMappingContext(DefaultMappingContext, 0);
		}
	}
}

void ACYPlayerCharacter::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);

	ACYPlayerState* PS = GetPlayerState<ACYPlayerState>();
	if (PS)
	{
		// ì„œë²„ì¸¡ì—ì„œ ì‹¤í–‰ë˜ëŠ” ASC ìºì‹± ë° ASC ì„¤ì •ìœ¼ë¡œì¨ í´ë¼ì´ì–¸íŠ¸ëŠ” OnRep_PlayerState()ì—ì„œ í•´ë‹¹ ë¡œì§ ì§„í–‰
		CYAbilitySystemComponent = Cast<UCYAbilitySystemComponent>(PS->GetAbilitySystemComponent());
		PS->GetAbilitySystemComponent()->InitAbilityActorInfo(PS, this);

		// ì„œë²„ì—ì„œë§Œ ì–´ë¹Œë¦¬í‹° ì„¸íŠ¸ë¥¼ ì´ˆê¸°í™”
		InitializeAbilitySets();
	}
}

void ACYPlayerCharacter::BeginPlay()
{
	Super::BeginPlay();
	
}

void ACYPlayerCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	
	UCYInputComponent* CYInputComponent = Cast<UCYInputComponent>(PlayerInputComponent);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_Move, ETriggerEvent::Triggered, this, &ACYPlayerCharacter::Input_Move, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_Look, ETriggerEvent::Triggered, this, &ACYPlayerCharacter::Input_Look, false);

	TArray<uint32> BindHandles;
	CYInputComponent->BindAbilityActions(DefaultInputConfig, this, &ThisClass::Input_AbilityInputTagStarted, &ThisClass::Input_AbilityInputTagPressed, &ThisClass::Input_AbilityInputTagReleased, /*out*/ BindHandles);

	// ì•„ì´í…œ ìƒí˜¸ì‘ìš© ì…ë ¥
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_Interact, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_Interact, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_Attack, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_Attack, false);
    
	// ì¸ë²¤í† ë¦¬ ìŠ¬ë¡¯ ì…ë ¥ (1~9ë²ˆ í‚¤)
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot1, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot1, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot2, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot2, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot3, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot3, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot4, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot4, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot5, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot5, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot6, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot6, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot7, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot7, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot8, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot8, false);
	CYInputComponent->BindNativeAction(DefaultInputConfig, CYGameplayTags::InputTag_UseSlot9, ETriggerEvent::Started, this, &ACYPlayerCharacter::Input_UseSlot9, false);
	
}

void ACYPlayerCharacter::Input_Move(const FInputActionValue& InputActionValue)
{
	if (AController* LocalController = GetController())
	{
		const FVector2D Value = InputActionValue.Get<FVector2D>();
		const FRotator MovementRotation(0.0f, LocalController->GetControlRotation().Yaw, 0.0f);

		if (Value.X != 0.0f)
		{
			const FVector MovementDirection = MovementRotation.RotateVector(FVector::RightVector);
			AddMovementInput(MovementDirection, Value.X);
		}

		if (Value.Y != 0.0f)
		{
			const FVector MovementDirection = MovementRotation.RotateVector(FVector::ForwardVector);
			AddMovementInput(MovementDirection, Value.Y);
		}
	}
}

void ACYPlayerCharacter::Input_Look(const FInputActionValue& InputActionValue)
{
	const FVector2D Value = InputActionValue.Get<FVector2D>();

	if (Value.X != 0.0f)
	{
		AddControllerYawInput(Value.X);
	}

	if (Value.Y != 0.0f)
	{
		AddControllerPitchInput(Value.Y);
	}
}

void ACYPlayerCharacter::Input_AbilityInputTagStarted(FGameplayTag InputTag)
{
	if (!CYAbilitySystemComponent.IsValid())
	{
		return;
	}
	
	CYAbilitySystemComponent->AbilityInputTagStarted(InputTag);
}

void ACYPlayerCharacter::Input_AbilityInputTagPressed(FGameplayTag InputTag)
{
	if (!CYAbilitySystemComponent.IsValid())
	{
		return;
	}

	CYAbilitySystemComponent->AbilityInputTagPressed(InputTag);
}

void ACYPlayerCharacter::Input_AbilityInputTagReleased(FGameplayTag InputTag)
{
	if (!CYAbilitySystemComponent.IsValid())
	{
		return;
	}

	CYAbilitySystemComponent->AbilityInputTagReleased(InputTag);
}

void ACYPlayerCharacter::OnRep_PlayerState()
{
	Super::OnRep_PlayerState();

	ACYPlayerState* PS = GetPlayerState<ACYPlayerState>();
	if (PS)
	{
		CYAbilitySystemComponent = Cast<UCYAbilitySystemComponent>(PS->GetAbilitySystemComponent());
		PS->GetAbilitySystemComponent()->InitAbilityActorInfo(PS, this);
	}
}

// ì•„ì´í…œ ìƒí˜¸ì‘ìš© ì…ë ¥
void ACYPlayerCharacter::Input_Interact(const FInputActionValue& InputActionValue)
{
    if (ItemInteractionComponent)
    {
        ItemInteractionComponent->InteractWithNearbyItem();
    }
}

void ACYPlayerCharacter::Input_Attack(const FInputActionValue& InputActionValue)
{
	// ğŸ”¥ í•œ ë²ˆì˜ ì¢Œí´ë¦­ìœ¼ë¡œ í•˜ë‚˜ì˜ ë™ì‘ë§Œ ì‹¤í–‰
	
	// 1. í˜„ì¬ ë“¤ê³  ìˆëŠ” ì•„ì´í…œì´ ìˆìœ¼ë©´ ì•„ì´í…œ ì‚¬ìš© (ìš°ì„ ìˆœìœ„ ë†’ìŒ)
	if (InventoryComponent && InventoryComponent->CurrentHeldItem)
	{
		bool bUsedItem = InventoryComponent->UseHeldItem();
		
		if (bUsedItem)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Used held item: %s"), 
				   *InventoryComponent->CurrentHeldItem->ItemName.ToString());
		}
		return; // ğŸ”¥ ì•„ì´í…œ ì‚¬ìš©í–ˆìœ¼ë©´ ì—¬ê¸°ì„œ ì¢…ë£Œ
	}
	
	// 2. ë¬´ê¸°ê°€ ì¥ì°©ë˜ì–´ ìˆìœ¼ë©´ ë¬´ê¸° ê³µê²©
	if (WeaponComponent && WeaponComponent->CurrentWeapon)
	{
		bool bUsedWeapon = WeaponComponent->PerformAttack();
		
		if (bUsedWeapon)
		{
			UE_LOG(LogTemp, Warning, TEXT("âš”ï¸ Attacked with weapon: %s"), 
				   *WeaponComponent->CurrentWeapon->ItemName.ToString());
		}
		return; // ğŸ”¥ ë¬´ê¸° ê³µê²©í–ˆìœ¼ë©´ ì—¬ê¸°ì„œ ì¢…ë£Œ
	}
	
	// 3. ë‘˜ ë‹¤ ì—†ìœ¼ë©´ ì¸ë²¤í† ë¦¬ ë””ë²„ê·¸ í‘œì‹œ
	ShowInventoryDebug();
	
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Yellow, 
			TEXT("No weapon equipped or item held - Press number keys to select"));
	}
}

void ACYPlayerCharacter::ShowInventoryDebug()
{
    if (InventoryComponent)
    {
        InventoryComponent->ShowInventoryDebug();
    }
}

// ì¸ë²¤í† ë¦¬ ìŠ¬ë¡¯ ì…ë ¥ (1~9ë²ˆ í‚¤)
void ACYPlayerCharacter::Input_UseSlot1(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(1); // ë¬´ê¸° ìŠ¬ë¡¯ 1
}

void ACYPlayerCharacter::Input_UseSlot2(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(2); // ë¬´ê¸° ìŠ¬ë¡¯ 2
}

void ACYPlayerCharacter::Input_UseSlot3(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(3); // ë¬´ê¸° ìŠ¬ë¡¯ 3
}

void ACYPlayerCharacter::Input_UseSlot4(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(4); // ì•„ì´í…œ ìŠ¬ë¡¯ 1
}

void ACYPlayerCharacter::Input_UseSlot5(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(5); // ì•„ì´í…œ ìŠ¬ë¡¯ 2
}

void ACYPlayerCharacter::Input_UseSlot6(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(6); // ì•„ì´í…œ ìŠ¬ë¡¯ 3
}

void ACYPlayerCharacter::Input_UseSlot7(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(7); // ì•„ì´í…œ ìŠ¬ë¡¯ 4
}

void ACYPlayerCharacter::Input_UseSlot8(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(8); // ì•„ì´í…œ ìŠ¬ë¡¯ 5
}

void ACYPlayerCharacter::Input_UseSlot9(const FInputActionValue& InputActionValue)
{
	if (InventoryComponent) InventoryComponent->HoldItem(9); // ì•„ì´í…œ ìŠ¬ë¡¯ 6
}